//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crude3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int id_produto { get; set; }
        public Nullable<int> id_tipo { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public string url { get; set; }
    }
}
